CREATE TABLE IF NOT EXISTS categories (
                                          category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          code VARCHAR(255) NOT NULL UNIQUE,
                                          name VARCHAR(255) NOT NULL,
                                          description VARCHAR(255),
                                          CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE IF NOT EXISTS employees (
                                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         employee_id VARCHAR(255) NOT NULL UNIQUE,
                                         first_name VARCHAR(255) NOT NULL,
                                         last_name VARCHAR(255) NOT NULL,
                                         email VARCHAR(255) NOT NULL UNIQUE,
                                         department VARCHAR(255),
                                         status VARCHAR(255) NOT NULL,
                                         CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS assets (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      asset_tag VARCHAR(50) NOT NULL UNIQUE,
                                      name VARCHAR(255) NOT NULL,
                                      serial_number VARCHAR(255) NOT NULL,
                                      status VARCHAR(255) NOT NULL,
                                      purchase_cost DECIMAL(10, 2) NOT NULL,
                                      purchase_date DATE NOT NULL,
                                      category_id BIGINT,
                                      assigned_employee_id BIGINT,
                                      CONSTRAINT pk_assets PRIMARY KEY (id),
                                      CONSTRAINT fk_assets_on_category FOREIGN KEY (category_id) REFERENCES categories (category_id),
                                      CONSTRAINT fk_assets_on_assigned_employee FOREIGN KEY (assigned_employee_id) REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS asset_assignment_history (
                                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                        asset_id BIGINT NOT NULL,
                                                        employee_id BIGINT NOT NULL,
                                                        assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                                        returned_at TIMESTAMP WITHOUT TIME ZONE,
                                                        CONSTRAINT pk_asset_assignment_history PRIMARY KEY (id),
                                                        CONSTRAINT fk_asset_assignment_history_on_asset FOREIGN KEY (asset_id) REFERENCES assets (id),
                                                        CONSTRAINT fk_asset_assignment_history_on_employee FOREIGN KEY (employee_id) REFERENCES employees (id)
);